apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: opensearch
  labels:
    app: opensearch
spec:
  replicas: 0
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      #tolerations:
      #- key: "node-role.kubernetes.io/control-plane"
      #  operator: "Exists"
      #  effect: "NoSchedule"
      #- key: "node.kubernetes.io/disk-pressure"
      #  operator: "Exists"
      #  effect: "NoSchedule"
      containers:
      - name: opensearch
        image: tristan090/opensearch:latest
        ports:
        - containerPort: 9200
        - containerPort: 9600
        env:
        - name: discovery.type
          value: "single-node"
        #- name: bootstrap.memory_lock
        #  value: "true"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: plugins.security.disabled  # Ajoutez cette variable
          value: "true"
        - name: opensearch.ssl.verificationMode
          value: "none"
        resources:  # Ajoutez cette section ici
          requests:
            cpu: "500m"    # Demande 0.5 CPU
            memory: "1Gi"  # Demande 1 Go de mémoire
          limits:
            cpu: "1000m"   # Limite à 1 CPU
            memory: "2Gi"  # Limite à 2 Go de mémoire
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opensearch
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9600
    targetPort: 9600
    name: transport