apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: default
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: tristan090/opensearch:latest
        ports:
        - containerPort: 9200
        - containerPort: 9600
        env:
        - name: discovery.type
          value: "single-node"
        - name: bootstrap.memory_lock
          value: "true"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: default
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9600
    targetPort: 9600
    name: transport