FROM opensearchproject/opensearch-dashboards:latest
# Ajoutez vos personnalisations ici, ex. :
# COPY config/opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
EXPOSE 5601
CMD ["/usr/share/opensearch-dashboards/bin/opensearch-dashboards"]