version: 2.1
jobs:
  build:
    docker:
      - image: cimg/docker:stable  # Image avec Docker préinstallé
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t tristan090/opensearch:latest -f opensearch/Dockerfile .
      - run:
          name: Build Dashboard Image
          command: docker build -t tristan090/opensearch-dashboards:latest -f dashboard/Dockerfile .
      - run:
          name: Push Docker Image
          command: |
            docker push tristan090/opensearch:latest
            docker push tristan090/opensearch-dashboards:latest
workflows:
  build:
    jobs:
      - build-and-push