version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/base:2023
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t tristan090/opensearch:latest .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push tristan090/opensearch:latest
workflows:
  build:
    jobs:
      - build-and-push