FROM opensearchproject/opensearch-dashboards:latest
# Ajoutez vos personnalisations ici, ex. :
#COPY opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
#RUN mkdir -p /var/log/opensearch-dashboards && \
#    chown -R opensearch-dashboards:opensearch-dashboards /var/log/opensearch-dashboards

EXPOSE 5601
CMD ["/usr/share/opensearch-dashboards/bin/opensearch-dashboards"]